### ISSUE TITLE
work for some games?

### ISSUE THREAD

**Issue by ISAAC300** [jtbuaa/HookDemo#1]
this hook work for some games like a Minecraft Pocket Edition? i need a ModLoader for make some mods for Minecraft on android pls you can help me?

**Comment by jtbuaa** [comment]
this demo show how to make native hook of current process. if you want a loader to hook other process, you can try the project DroidPlugin.

**Comment by ISAAC300** [comment]
@jtbuaa wow thanks.  ;) maybe work for me. big thanks.
